"use client";

import { motion } from "framer-motion";
import { Music2, Mic2, Wand2, Play, Download, BarChart3 } from "lucide-react";
import { APP_TITLE } from "@/lib/constants";
import { CreateBattleCTA } from "./create-battle-cta";
import Image from "next/image";

interface MakeSongHighlightProps {
  isAuthenticated: boolean;
}

export function MakeSongHighlight({ isAuthenticated }: MakeSongHighlightProps) {
  return (
    <section className="-mt-px -mb-px pt-2 pb-4 px-4 relative overflow-hidden bg-linear-to-b from-stage-dark via-purple-950/20 to-stage-dark border-none">
      {/* Background Glows */}
      <div className="absolute top-20 left-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-20 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto text-center mb-12 relative z-10">
        <h2 className="text-4xl md:text-6xl font-bold font-(family-name:--font-bebas-neue) text-white leading-tight mb-6">
          Turn Battles{" "}
          <span className="text-transparent bg-clip-text bg-linear-to-r from-purple-400 to-blue-400">
            Into Hits
          </span>
        </h2>
        <div className="inline-flex items-center justify-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-300 text-sm font-medium mb-4">
          <Wand2 className="w-4 h-4" />
          <span>AI Music Generation</span>
        </div>
        <p className="text-xl text-gray-400 leading-relaxed max-w-2xl mx-auto">
          Don't let the bars fade away. Convert your best rap battles into
          full-length tracks with AI-generated beats, vocals, and cover art.
        </p>
      </div>

      <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 items-center relative z-10">
        {/* Left Content */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="space-y-8"
        >
          <div className="space-y-4">
            <div className="flex items-start gap-4">
              <div className="p-3 rounded-lg bg-purple-500/10 text-purple-400">
                <Mic2 className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white mb-1">
                  From Stage to Studio
                </h3>
                <p className="text-gray-400">
                  Your lyrics are transformed into professional-sounding verses.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="p-3 rounded-lg bg-blue-500/10 text-blue-400">
                <Music2 className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white mb-1">
                  Choose Your Style
                </h3>
                <p className="text-gray-400">
                  Select from G-Funk, Boom Bap, or Trap beats to match the vibe.
                </p>
              </div>
            </div>
          </div>

          <div className="pt-4 flex justify-center">
            <CreateBattleCTA
              isAuthenticated={isAuthenticated}
              title="Create a Track"
            />
          </div>
        </motion.div>

        {/* Right Visual */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="relative"
        >
          {/* Mock Player Card */}
          <div className="relative bg-gray-900/60 backdrop-blur-md border border-white/10 rounded-2xl p-6 shadow-2xl transform rotate-3 hover:rotate-0 transition-transform duration-500 overflow-hidden">
            <div className="flex items-center gap-6 mb-6">
              <div className="relative w-24 h-24 rounded-lg overflow-hidden shadow-lg shrink-0 border border-white/10">
                <Image
                  src="/marketing/album-cover-example.webp"
                  alt="Album Cover"
                  fill
                  className="object-cover"
                />
              </div>
              <div className="space-y-1">
                <div className="text-xs text-purple-300 font-medium tracking-wider uppercase">
                  Now Playing
                </div>
                <h3 className=" text-xl md:text-2xl font-bold text-white">
                  Tyler, The Creator vs. Tim Dog
                </h3>
                <p className="text-gray-400">
                  G-Funk Style • Generated by {APP_TITLE}
                </p>
              </div>
            </div>

            {/* Waveform Visualization Mock */}
            <div className="h-16 flex items-end justify-between gap-1 mb-6 px-2">
              {[...Array(20)].map((_, i) => (
                <div
                  key={i}
                  className="w-2 bg-purple-500/50 rounded-t-sm animate-pulse"
                  style={{
                    height: `${Math.max(20, Math.random() * 100)}%`,
                    animationDelay: `${i * 0.05}s`,
                  }}
                />
              ))}
            </div>

            {/* Controls */}
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <button className="w-12 h-12 rounded-full bg-white text-black flex items-center justify-center hover:scale-105 transition-transform">
                  <Play className="w-5 h-5 ml-1 fill-current" />
                </button>
                <div className="text-sm font-mono text-gray-400">
                  1:24 / 3:45
                </div>
              </div>
              <div className="flex gap-2">
                <button className="p-2 rounded-full hover:bg-white/10 text-gray-400 hover:text-white transition-colors">
                  <BarChart3 className="w-5 h-5" />
                </button>
                <button className="p-2 rounded-full hover:bg-white/10 text-gray-400 hover:text-white transition-colors">
                  <Download className="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>

          {/* Floating Elements */}
          <div className="absolute -top-6 -right-6 w-20 h-20 bg-yellow-500/20 rounded-full blur-xl animate-pulse" />
        </motion.div>
      </div>
    </section>
  );
}
